name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::192357816036:role/github-push-docker-image
        aws-region: us-east-1

    - name: Docker Login
      uses: docker/login-action@v1.12.0
      with:
        registry: public.ecr.aws

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1.6.0

    - name: Docker Build
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ./debug
        platforms: linux/amd64,linux/arm64
        push: true
        tags: public.ecr.aws/jacknagel/debug:latest
