name: Docker Image CI

on:
  push:
    branches:
    - main

jobs:

  build:
    environment: build

    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
        - name: debug
          platforms: linux/amd64,linux/arm64
        - name: skeema
          platforms: linux/amd64
          build-args: SKEEMA_VERSION

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::192357816036:role/github-push-docker-image
        aws-region: us-east-1

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: public.ecr.aws

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker Build
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: ./${{ matrix.name }}
        platforms: ${{ matrix.platforms }}
        push: true
        tags: public.ecr.aws/jacknagel/${{ matrix.name }}:latest
        build-args: ${{ matrix.build-args }}
